var maintenance = [
  { id: 1, filename: "project1" },
  { id: 2, filename: "project2" },
  { id: 3, filename: "project3" },
  { id: 4, filename: "project4" },
  { id: 5, filename: "project5" },
  { id: 6, filename: "project6" },
  { id: 7, filename: "project7" },
  { id: 8, filename: "project8" },
  { id: 9, filename: "project9" },
  { id: 10, filename: "project10" },
  { id: 11, filename: "project11" },
  { id: 12, filename: "project12" },
  { id: 13, filename: "project13" },
]

var renovation = [
  { id: 1, filename: "project1" },
  { id: 2, filename: "project2" },
  { id: 3, filename: "project3" },
  { id: 4, filename: "project4" },
  { id: 5, filename: "project5" },
  { id: 6, filename: "project6" },
  { id: 7, filename: "project7" },
  { id: 8, filename: "project8" },
  { id: 9, filename: "project9" },
  { id: 10, filename: "project10" },
  { id: 11, filename: "project11" },
  { id: 12, filename: "project12" },
  { id: 13, filename: "project13" },
  { id: 14, filename: "project14" },
  { id: 15, filename: "project15" },
]

var construction = [
  { id: 1, filename: "project1" },
  { id: 2, filename: "project2" },
  { id: 3, filename: "project3" },
  { id: 4, filename: "project4" },
  { id: 5, filename: "project5" },
  { id: 6, filename: "project6" },
  { id: 7, filename: "project7" },
  { id: 8, filename: "project8" },
  { id: 9, filename: "project9" },
  { id: 10, filename: "project10" },
  { id: 11, filename: "project11" },
  { id: 12, filename: "project12" },
]